org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true

mod_id=myragdoll
mod_name=My Ragdoll
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.example.myragdoll
mod_authors=hapermeh
mod_description=Custom togglable ragdoll mod template for NeoForge 1.21.1. Fork of Sable: Ragdoll

neoforge_version=21.1.65